const projects = [
  {
    id: '0',
    year: '2023',
    name: 'Fight Club',
    client: 'Personal Project',
    description: 'Personal illustration',
  },
  {
    id: '1',
    year: '2023',
    name: 'Wizard Bot',
    client: 'Client:Bees Knees Print Studio',
    description: '6 layers t-shirt design for screen printing',
  },
  {
    id: '2',
    year: '2023',
    name: 'Girl Biking',
    client: 'Personal Project',
    description: 'Personal illustration',
  },
  {
    id: '3',
    year: '2023',
    name: 'Pink Robot',
    client: 'Breed',
    description: 'Shapes inspired from japanese mechas',
  },
  {
    id: '4',
    year: '2023',
    name: 'Cubix',
    client: 'Null NYC',
    description:
      'Design of animated television series Cubix: Robots For Everyone',
  },
  {
    id: '5',
    year: '2023',
    name: 'Cyber II',
    client: 'Personal Project',
    description: 'Design inspired by retro video games and space ships',
  },
  {
    id: '6',
    year: '2023',
    name: 'Death Of Robots 2',
    client: 'Personal Project',
    description: 'Design inspired by old PS2 CD graphics',
  },
  {
    id: '7',
    year: '2023',
    name: 'Blow Up The Neighborhood',
    client: `Don't Blame The Kids`,
    description: 'Design inspired by old cartoon show Codename: Kids Next Door',
  },
  {
    id: '8',
    year: '2023',
    name: 'Alien Girl',
    client: 'Icy',
    description: 'Experimenting with brushes and shading',
  },
  {
    id: '9',
    year: '2023',
    client: 'Icy',
    name: 'Subzero vs Scorpion',
    description: 'Design inspired by the classic video game, Mortal Kombat',
  },
  {
    id: '10',
    year: '2023',
    name: 'Taxi Robot & The Chase',
    client: 'Monday Suck',
    description: 'Experimenting with shading and composition',
  },
  {
    id: '11',
    year: '2023',
    name: 'Pixie Robot',
    client: 'Pixie',
    description: 'Typography and character design work',
  },
  {
    id: '12',
    year: '2023',
    name: 'Racing Bots',
    client: 'Personal Project',
    description: 'Design inspired by Nascar cars',
  },
  {
    id: '13',
    year: '2023',
    name: 'Robot Nun',
    client: 'Death Division',
    description:
      'Design inspired by gothic architecture, churches and anime characters',
  },
  {
    id: '14',
    year: '2023',
    name: 'Robot Shooting',
    client: 'Death Division',
    description: 'Design inspired by Halo guns',
  },
  {
    id: '15',
    year: '2023',
    name: 'Space Bunny',
    client: 'Death Division',
    description: 'Experimenting with perspective, typography and brushes',
  },
  {
    id: '16',
    year: '2023',
    name: 'Hot-lime Bling & Smooth Caramel',
    client: `Toby's Estate`,
    description:
      'Designs inspired by the singles: Drake-Hotline Bling & Michael Jackson-Smooth Criminal',
  },
  {
    id: '17',
    year: '2023',
    name: 'Basketball Robot',
    client: 'Voltage',
    description: 'Design inspired by construction machines',
  },
  {
    id: '18',
    year: '2023',
    name: 'Voltage Sport Stickers',
    client: 'Voltage',
    description: 'Graphics inspired by sports',
  },
  {
    id: '19',
    year: '2023',
    name: 'Zombie Land',
    client: 'Death Division',
    description: `Graphic inspired by 80's animes atmosphere`,
  },
];

export default projects;
